name: Semantic Release
description: |
  Automated release process using Semantic Release

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  issues: write
  packages: write
  pull-requests: write
  security-events: write

jobs:
  analyze_code:
    name: Analyze
    uses: cabrera-evil/workflows/.github/workflows/code-analysis.yaml@master
    with:
      default_branch: ${{ github.event.repository.default_branch }}
      push_before_sha: ${{ github.event.before }}
      push_base_sha: ${{ github.event.base_ref }}
    secrets: inherit

  release:
    name: Release
    needs: analyze_code
    uses: cabrera-evil/workflows/.github/workflows/semantic-release.yaml@master
    secrets: inherit
